services:
  db:
    image: postgres:14.8-alpine3.18
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_HOST_AUTH_METHOD: trust
      LANG: en_US.utf8
      LANGUAGE: en_US:en
      LC_ALL: en_US.utf8
      PORT: 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - car_bot_network

  bot:
    image: sf-car-bot:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - car_bot_network
    volumes:
      - media_cars:/app/media/cars

volumes:
  media_cars: 
    driver: local
  pgdata:
    driver: local

networks:
  car_bot_network:
    driver: overlay
