services:
  car_bot:
    image: sf-car-bot:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    env_file:
      - .env
    networks:
      - car_bot_network
    volumes:
      - media_cars:/app/media/cars

volumes:
  media_cars: 
    driver: local

networks:
  car_bot_network:
    driver: overlay
